batch_size: 32
epochs: 30
lr: 2e-5
weight_decay: 0.01
img_size: 384
max_tokens: 30
warmup_epochs: 3
cosine_lr: true

data_root: /root/autodl-tmp/paper_data/coco_data
data_referit_root: /root/autodl-tmp/paper_data/referit
output_dir: output/refersam_bert/

sam_type: vit_b
checkpoint: /root/autodl-tmp/paper_data/weight/sam/sam_vit_b_01ec64.pth

tokenizer_type: bert
ck_bert: /root/autodl-tmp/vision_paper/ReferSAM/bert-base-uncased
clip_path: null

precision: fp32
# use_vl_adapter: False 给我自己写的模型使用的

pre_train_path: /root/autodl-tmp/vision_paper/ReferSAM/output/refersam_bert/enhanced_multi_dataset_best_iou_miou_model
# resume: /root/autodl-tmp/vision_paper/ReferSAM/output/refersam_bert/enhanced_multi_dataset_checkpoint_epoch_37
