batch_size: 12
epochs: 15
lr: 2e-5
weight_decay: 0.01

data_root: /root/autodl-tmp/paper_data/coco_data
output_dir: output/refersam_bert

sam_type: vit_b
checkpoint: /root/autodl-tmp/paper_data/weight/sam/sam_vit_b_01ec64.pth

tokenizer_type: bert
ck_bert: /root/autodl-tmp/vision_paper/ReferSAM/bert-base-uncased
clip_path: null

precision: fp32
use_vl_adapter: False

pre_train_path: /root/autodl-tmp/vision_paper/ReferSAM/output/refersam_bert/checkpoint_epoch_15.pt
